import type { EnglishResources, LocaleResourceShape } from './en'

const ptBR = {
  meta: {
    title: 'Solitude — Duelo de Prioridades em Vinil',
    description: 'Transforme sua lista de desejos de vinil em um ranking sincero, decidido duelo a duelo.',
  },
  language: { label: 'Idioma da interface', english: 'Usar inglês', portuguese: 'Usar português do Brasil' },
  common: {
    back: 'Voltar', save: 'Salvar', remove: 'Remover', choose: 'Escolher', retry: 'Tentar novamente', loading: 'Carregando…', unknownArtist: 'Artista desconhecido', optional: 'opcional',
    collection_one: '{{count}} coleção', collection_other: '{{count}} coleções', record_one: '{{count}} disco', record_other: '{{count}} discos', album_one: '{{count}} álbum', album_other: '{{count}} álbuns', line_one: '{{count}} linha', line_other: '{{count}} linhas', choice_one: '{{count}} escolha', choice_other: '{{count}} escolhas', track_one: '{{count}} faixa', track_other: '{{count}} faixas',
  },
  shell: {
    homeLabel: 'Voltar à biblioteca de coleções', footer: 'Feito para ouvir com atenção. Sua biblioteca fica neste navegador.', metadataBy: 'Metadados por', coverArtBy: 'Capas por', savedStatus_one: '{{collections}} · salva neste dispositivo', savedStatus_other: '{{collections}} · salvas neste dispositivo', dismissNotice: 'Fechar aviso',
  },
  lyrics: { stable: 'In my solitude' },
  vibes: { lateNight: 'Madrugada', sundayMorning: 'Manhã de domingo', roadTrip: 'Pé na estrada', deepFocus: 'Foco profundo', rainyDay: 'Dia chuvoso', party: 'Festa' },
  library: {
    setupBack: '← Voltar', setupStep: 'Nova coleção · Etapa 1 de 3', setupTitleBefore: 'Vamos preparar o ', setupTitleEmphasis: 'palco.', setupIntro: 'Dê um nome e um clima a este grupo. É só para você—uma forma de lembrar o que buscava quando o reuniu.', nameLabel: 'Nome da coleção', namePlaceholder: 'Discos da madrugada', moodLegend: 'Qual é o clima?', noteLabel: 'Um recado para você no futuro', notePlaceholder: 'Discos para as longas noites de inverno…', addRecords: 'Adicionar seus discos →', nextPaste: 'A seguir: cole sua lista de desejos.', eyebrow: 'Prioridades do vinil, resolvidas', heroFirst: 'O que', heroSecond: 'merece ser o', heroEmphasis: 'próximo disco?', lede: 'Sua lista de desejos é maior que o orçamento—e essa é a graça. Coloque os discos frente a frente, confie no instinto e deixe o Solitude definir a ordem, uma escolha sincera de cada vez.', startRanking: 'Começar um ranking →', openStarted: 'ou abra uma coleção que você começou', howItWorks: 'Como o Solitude funciona', stepPaste: 'Cole', stepChoose: 'Escolha', stepRanking: 'Um ranking confiável', previewLabel: 'Prévia de um duelo do ranking', previewHeading: 'Um pouco do ritual', previewCount: '1 de muitos', or: 'ou', previewBody: 'Todo ranking nasce de momentos assim—escolha o disco que você preferiria comprar agora ou declare empate.', fictionalCover: 'Capa fictícia de {{title}}, de {{artist}}', shelves: 'As prateleiras', collectionsTitle: 'Suas coleções', emptyTitle: 'Sua estante está silenciosa', emptyBody: 'Crie uma coleção e cole os discos que está considerando.', createFirst: 'Criar sua primeira coleção', noRecords: 'Ainda sem discos', updated: '{{records}} · Atualizada em {{date}}', collectionName: 'Nome da coleção', resumeLabel: 'Retomar duelo de {{name}}', battleInProgress: 'Duelo em andamento', choicesSaved_one: '{{choices}} salva', choicesSaved_other: '{{choices}} salvas', resume: 'Retomar →', startCardRanking: 'Começar ranking', editList: 'Editar lista', addRecordsShort: 'Adicionar discos', renameLabel: 'Renomear {{name}}', deleteLabel: 'Excluir {{name}}', history: 'Histórico de rankings', view: 'Ver', newCollection: 'Nova coleção', newCollectionBody: 'Comece outro ranking com uma lista de desejos.', deleteConfirm: 'Excluir “{{name}}” e todo o histórico de rankings?',
  },
  import: {
    back: '← Coleções', eyebrow: '01 · Monte a pilha de audição', titleBefore: 'Cole sua ', titleEmphasis: 'lista de desejos.', intro: 'Um álbum por linha. Entendemos hífens, tabulações, “Álbum by Artista” e linhas só com o título.', listLabel: 'Lista de álbuns', uniqueCount: '{{count}}/100 únicos', placeholder: 'Clube da Esquina - Milton Nascimento & Lô Borges\nAcabou Chorare — Novos Baianos\nElis & Tom by Elis Regina & Antônio Carlos Jobim', artistFirst: 'O artista vem primeiro', artistFirstHelp: 'Inverta as colunas Artista e Álbum em todas as linhas com duas colunas.', preview: 'Prévia da importação', empty: 'Os álbuns interpretados aparecerão aqui.', couldNotRead: 'Não foi possível ler a linha', duplicate: 'Duplicata da linha {{line}}', minimum: 'Adicione pelo menos dois álbuns únicos para continuar.', duplicates_one: 'Resolva {{count}} linha duplicada antes de continuar.', duplicates_other: 'Resolva {{count}} linhas duplicadas antes de continuar.', invalid_one: 'Corrija {{count}} linha ilegível ou acima do limite.', invalid_other: 'Corrija {{count}} linhas ilegíveis ou acima do limite.', warning: 'Um ranking profundo de {{count}} álbuns pode demorar bastante. O modo Rápido continuará disponível.', next: 'A seguir, você revisará os metadados e as capas.', review: 'Revisar {{count}} álbuns →',
  },
  parser: { empty: 'Linha vazia', missingTitle: 'Falta o título do álbum', missingArtist: 'Falta o artista', limit: 'Somente os primeiros {{limit}} álbuns únicos podem ser importados' },
  review: {
    back: '← Importação', eyebrow: '02 · Confira as capas', titleBefore: 'Revise seus ', titleEmphasis: 'discos.', intro: 'Vamos resolver as correspondências óbvias em silêncio. Você só precisa intervir quando o catálogo tiver dúvida.', consoleLabel: 'Status das correspondências no catálogo', session: 'Sessão do catálogo', searched: '{{searched}} de {{total}} pesquisados', status: '{{matched}} correspondentes · {{unresolved}} precisam de atenção', matchingHelp: 'As correspondências fortes se recolhem assim que chegam. As capas continuam em paralelo.', idleHelp: 'Resultados em cache aparecem na hora; novas buscas no MusicBrainz respeitam o ritmo do serviço.', matching: 'Comparando…', matchUnresolved: 'Comparar {{count}} pendentes', allMatched: 'Tudo correspondente', autoCorrected: 'Corrigido automaticamente · {{confidence}}%', catalogMatchedConfidence: 'Catálogo correspondente · {{confidence}}%', catalogMatched: 'Catálogo correspondente', chooseMatch: 'Escolha uma correspondência', searchError: 'Erro na busca', manualDetails: 'Dados manuais', notMatched: 'Sem correspondência', editDetails: 'Editar dados', rematch: 'Buscar novamente', coverArriving: 'A capa está chegando do acervo…', coverMissingEdit: 'Sem capa no acervo—usamos uma alternativa inspirada no artista. Edite para adicionar uma URL HTTPS personalizada.', coverMissingAdd: 'Sem capa no acervo—usamos uma alternativa inspirada no artista. Adicione uma URL HTTPS personalizada, se tiver.', coverFailed: 'A consulta da capa falhou.', retryCover: 'Tentar capa novamente', listening: 'Procurando uma correspondência…', albumTitle: 'Título do álbum', artist: 'Artista', year: 'Ano', coverUrl: 'URL HTTPS da capa', searching: 'Buscando…', findBetter: 'Encontrar resultado melhor', doneEditing: 'Concluir edição', duplicate: 'Este álbum duplica outro da coleção.', invalidCover: 'URLs de capa personalizadas devem começar com https://', matchesFor: 'Resultados para {{title}}', catalogUnsure: 'O catálogo está em dúvida.', catalogUnsureHelp: 'Escolha a capa certa.', confidence: '{{confidence}}% de confiança', lowConfidence: 'Baixa confiança', uniqueRange: '{{albums}} · Mínimo 2, máximo 100', continue: 'Escolher modo de ranking →', noMatches: 'Nenhum resultado encontrado no catálogo. Você pode continuar manualmente.', searchFailed: 'A busca no catálogo falhou. Tente novamente em instantes.',
  },
  modes: {
    quick: { name: 'Rápido', eyebrow: 'Uma primeira prensagem', description: 'Três rodadas todos-contra-todos com ordem semeada, avaliadas como um conjunto conectado de preferências.', pro: 'O caminho mais curto para uma boa lista final.', con: 'O meio do ranking é aproximado.' },
    balanced: { name: 'Equilibrado', eyebrow: 'O favorito da casa', description: 'Um duelo adaptativo que investe o orçamento fixo em encontros incertos e pouco explorados.', pro: 'Ótimo equilíbrio entre velocidade e confiança.', con: 'Nem todos os pares se enfrentam diretamente.' },
    thorough: { name: 'Minucioso', eyebrow: 'A audição profunda', description: 'Cada par possível se enfrenta exatamente uma vez.', pro: 'Cobertura máxima de comparações diretas.', con: 'Coleções grandes levam bastante tempo.' },
    recommended: 'Recomendado', back: '← Revisar discos', eyebrow: '03 · Defina a profundidade', titleBefore: 'Quanta certeza você\nquer ', titleEmphasis: 'sentir?', intro: 'Você pode escolher outro modo antes de cada rodada. Escolha um dos discos ou declare empate quando nenhum vier primeiro.', longWarningTitle: 'Uma pilha de respeito.', longWarning: 'O modo Minucioso exige {{count}} escolhas; considere Rápido ou Equilibrado.', groupLabel: 'Modo de ranking', exactly: 'Exatamente', battles_one: '{{formattedCount}} duelo', battles_other: '{{formattedCount}} duelos', about: 'Cerca de', seedHelp: 'A ordem inicial, os desempates adaptativos e a posição esquerda/direita são aleatórios e usam uma semente salva.', begin: 'Começar duelo {{mode}} →', modeLabel: 'Modo {{mode}}',
  },
  duration: { seconds: '{{count}} s', minutes: '{{count}} min', hours: '{{count}} h', hoursMinutes: '{{hours}} h {{minutes}} min' },
  battle: {
    preparing: 'Preparando seu ranking…', exit: '← Salvar e sair', undo: '↶ Desfazer', restart: 'Recomeçar', progress: 'Duelo {{current}}', of: 'de {{total}}', remaining: 'Cerca de {{duration}} restantes', chooseBetween: 'Escolha entre {{leftTitle}}, de {{leftArtist}}, e {{rightTitle}}, de {{rightArtist}}.', eyebrow: 'Confie no seu instinto', titleBefore: 'Qual disco vem ', titleEmphasis: 'primeiro?', prompt: 'Escolha o álbum que você preferiria comprar agora ou declare empate quando nenhum vier primeiro.', chooseRecord: 'Escolher este disco', cantDecide: 'Não consigo decidir', or: 'ou', keyboard: 'Teclado:', keyboardLeft: 'para a esquerda', keyboardTie: 'para empate', keyboardRight: 'para a direita', restartConfirm: 'Recomeçar esta rodada? As escolhas salvas desta rodada serão apagadas.',
  },
  trackReview: {
    noAlbums: 'Não há álbuns para revisar', returnResults: 'Voltar aos resultados', saveReturn: '← Salvar e voltar aos resultados', progress: '{{current}} de {{total}}', eyebrow: 'Uma audição mais atenta · opcional', titleLabel: 'Guarde as músicas que ficam com você.', titleBefore: 'Guarde as músicas que\n', titleEmphasis: 'ficam com você.', intro: 'Músicas intocadas são neutras. Marque o coração das faixas de que gosta; as músicas nunca são comparadas entre si.', edition: 'Edição', editionOption: '{{title}} · {{tracks}}{{date}}', loadingTracklist: 'Carregando lista de faixas', manualTitle: 'Digite um resumo simples do álbum', manualHelp: 'Use esta opção quando o catálogo não tiver uma edição adequada. Informe de quantas faixas você gosta.', totalTracks: 'Total de faixas', liked: 'Curtidas', likedTracks: 'Faixas curtidas', useCatalog: 'Usar a lista do catálogo', like: 'Curtir {{title}}', unlike: 'Descurtir {{title}}', likeTitle: 'Curtir', unlikeTitle: 'Descurtir', noTracklist: 'Nenhuma lista de faixas adequada foi encontrada para este álbum.', enterManual: 'Inserir totais manualmente', moreEditions: 'Mais edições', loadingMore: 'Carregando…', skip: 'Pular álbum não ouvido', finish: 'Concluir revisão das músicas', saveNext: 'Salvar e ir ao próximo álbum →', reviewing: 'Revisando {{title}}, de {{artist}}, álbum {{current}} de {{total}}.', loadFailed: 'Não foi possível carregar a lista de faixas.', moreFailed: 'Não foi possível carregar mais edições.',
  },
  manualErrors: { wholeNumbers: 'Use números inteiros iguais ou maiores que zero.', oneTrack: 'Informe pelo menos uma faixa.', likedExceedsTotal: 'O número de faixas curtidas não pode superar o total.' },
  results: {
    eyebrow: 'A sequência final', titleLabel: 'Seu próximo disco está decidido.', titleBefore: 'Seu próximo disco\nestá ', titleEmphasis: 'decidido.', summary_one: '{{choices}} formou este ranking {{mode}} para {{collection}}.', summary_other: '{{choices}} formaram este ranking {{mode}} para {{collection}}.', legacyTitle: 'Este ranking usa o modelo original do Solitude.', legacyBody: 'Ele permanece exatamente como você o concluiu. Faça outro ranking quando quiser um resultado Bradley–Terry.', viewLabel: 'Visualização do ranking', heart: 'Coração', recordValue: 'Valor do disco', balance: 'Seu equilíbrio', heartWeight: 'Peso do coração', songs: 'Músicas', heartNote: 'Somente escolhas entre álbuns.', recordNote: 'Evidências das músicas com uma priori de contração de oito faixas.', balanceNote: 'Evidências padronizadas de coração e músicas, combinadas ao vivo.', topPick: 'Escolha nº 1', heartScore: '{{score}} coração', recordScore: '{{score}}% disco', balanceScore: '{{score}} equilíbrio', notReviewed: 'Não revisados', notReviewedBody: 'Estes álbuns ficam fora do Valor do disco até você revisar ou informar suas músicas.', disagreementEyebrow: 'Onde coração e músicas seguem rumos diferentes', disagreement: '{{heartAlbum}} vence nos duelos de álbuns, enquanto {{trackAlbum}} tem evidências mais fortes nas músicas.', encore: 'Um bis opcional', deeperTitle: 'Quer ir mais fundo nas músicas?', deeperBody: 'Marque o coração ao lado das faixas de que gosta para revelar o Valor do disco e Seu equilíbrio. Seu ranking de coração já está completo e não será substituído.', reviewSongs: 'Revisar as músicas', keepRanking: 'Manter este ranking', rankAgainNew: 'Refazer com o novo modelo', rankAgain: 'Fazer outro ranking', reviewSongsShort: 'Revisar músicas', backCollections: 'Voltar às coleções', undo: '↶ Desfazer última escolha',
  },
  albumArt: { missing: 'Sem capa para {{title}}, de {{artist}}', cover: 'Capa de {{title}} — {{artist}}' },
  notices: { recovered: 'Os dados salvos estavam ilegíveis, então o Solitude abriu uma biblioteca nova.', saveFailed: 'Não foi possível salvar sua última alteração. O armazenamento do navegador pode estar cheio ou indisponível.', invalidNavigation: 'A página restaurada não era mais válida, então o Solitude voltou à sua biblioteca.' },
  fallback: { collectionMissing: 'Coleção não encontrada', nothingResume: 'Não há nada para retomar', returnLibrary: 'Voltar à biblioteca' },
} as const satisfies LocaleResourceShape<EnglishResources>

export default ptBR
