import type { EnglishResources, LocaleResourceShape } from './en'

const ptBR = {
  meta: {
    title: 'Solitude | Prioridades em vinil',
    description: 'Transforme sua lista de desejos em um ranking de discos, escolha por escolha.',
  },
  language: { label: 'Idioma da interface', english: 'Usar inglês', portuguese: 'Usar português do Brasil' },
  common: {
    back: 'Voltar', save: 'Salvar', remove: 'Remover', choose: 'Escolher', retry: 'Tentar de novo', loading: 'Carregando…', unknownArtist: 'Artista desconhecido', optional: 'opcional',
    collection_one: '{{count}} coleção', collection_other: '{{count}} coleções', record_one: '{{count}} disco', record_other: '{{count}} discos', album_one: '{{count}} álbum', album_other: '{{count}} álbuns', line_one: '{{count}} linha', line_other: '{{count}} linhas', choice_one: '{{count}} escolha', choice_other: '{{count}} escolhas', track_one: '{{count}} faixa', track_other: '{{count}} faixas',
  },
  shell: {
    homeLabel: 'Voltar para a lista de coleções', footer: 'Feito para ouvir com calma. Sua biblioteca fica salva neste navegador.', metadataBy: 'Metadados por', coverArtBy: 'Capas por', savedStatus_one: '{{collections}} · salva neste dispositivo', savedStatus_other: '{{collections}} · salvas neste dispositivo', dismissNotice: 'Fechar aviso',
  },
  lyrics: { stable: 'In my solitude' },
  vibes: { lateNight: 'Madrugada', sundayMorning: 'Manhã de domingo', roadTrip: 'Pé na estrada', deepFocus: 'Concentração', rainyDay: 'Dia chuvoso', party: 'Festa' },
  library: {
    setupBack: '← Voltar', setupStep: 'Nova coleção · Etapa 1 de 3', setupTitleBefore: 'Crie sua ', setupTitleEmphasis: 'coleção.', setupIntro: 'Dê um nome e escolha um clima para a coleção. Assim, você vai lembrar o que procurava quando montou a lista.', nameLabel: 'Nome da coleção', namePlaceholder: 'Discos da madrugada', moodLegend: 'Qual é o clima?', noteLabel: 'Uma nota para você no futuro', notePlaceholder: 'Discos para as longas noites de inverno…', addRecords: 'Adicionar discos →', nextPaste: 'Depois, cole sua lista de desejos.', eyebrow: 'Escolha seu próximo disco', heroFirst: 'Qual disco', heroSecond: 'você quer comprar', heroEmphasis: 'primeiro?', lede: 'Cole sua lista de desejos, compare dois discos por vez e escolha qual você compraria primeiro. O ranking nasce dessas escolhas.', startRanking: 'Criar um ranking →', openStarted: 'ou retome uma coleção', howItWorks: 'Como funciona', stepPaste: 'Cole sua lista', stepChoose: 'Compare os discos', stepRanking: 'Veja o ranking', previewLabel: 'Exemplo de um duelo do ranking', previewHeading: 'Exemplo de comparação', previewCount: '1 de várias', or: 'ou', previewBody: 'Escolha qual dos dois discos você compraria primeiro ou marque empate.', fictionalCover: 'Capa fictícia de {{title}}, de {{artist}}', shelves: 'Na sua estante', collectionsTitle: 'Suas coleções', emptyTitle: 'Nenhuma coleção por aqui', emptyBody: 'Crie uma coleção com os discos que você está pensando em comprar.', createFirst: 'Criar a primeira coleção', noRecords: 'Ainda sem discos', updated: '{{records}} · Atualizada em {{date}}', collectionName: 'Nome da coleção', resumeLabel: 'Retomar ranking de {{name}}', battleInProgress: 'Ranking em andamento', choicesSaved_one: '{{choices}} salva', choicesSaved_other: '{{choices}} salvas', resume: 'Retomar →', startCardRanking: 'Começar ranking', editList: 'Editar lista', addRecordsShort: 'Adicionar discos', renameLabel: 'Renomear {{name}}', deleteLabel: 'Excluir {{name}}', history: 'Histórico de rankings', view: 'Ver', newCollection: 'Nova coleção', newCollectionBody: 'Monte outro ranking a partir de uma lista de desejos.', deleteConfirm: 'Excluir “{{name}}” e todo o histórico de rankings?',
  },
  import: {
    back: '← Coleções', eyebrow: '01 · Adicione os discos', titleBefore: 'Cole sua ', titleEmphasis: 'lista de desejos.', intro: 'Use um álbum por linha. Separe título e artista com hífen ou tabulação, use “Álbum by Artista” ou informe apenas o título.', listLabel: 'Lista de álbuns', uniqueCount: '{{count}}/100 únicos', placeholder: 'Clube da Esquina - Milton Nascimento & Lô Borges\nAcabou Chorare - Novos Baianos\nElis & Tom by Elis Regina & Antônio Carlos Jobim', artistFirst: 'O artista vem primeiro', artistFirstHelp: 'Troque a ordem das colunas Artista e Álbum em todas as linhas que tiverem duas colunas.', preview: 'Prévia da importação', empty: 'Os álbuns identificados aparecerão aqui.', couldNotRead: 'Não foi possível ler a linha', duplicate: 'Repete a linha {{line}}', minimum: 'Adicione pelo menos dois álbuns diferentes para continuar.', duplicates_one: 'Corrija {{count}} linha repetida antes de continuar.', duplicates_other: 'Corrija {{count}} linhas repetidas antes de continuar.', invalid_one: 'Corrija {{count}} linha ilegível ou acima do limite.', invalid_other: 'Corrija {{count}} linhas ilegíveis ou acima do limite.', warning: 'Comparar {{count}} álbuns no modo Minucioso pode levar bastante tempo. O modo Rápido continuará disponível.', next: 'Depois, confira os dados e as capas.', review: 'Revisar {{count}} álbuns →',
  },
  parser: { empty: 'Linha vazia', missingTitle: 'Falta o título do álbum', missingArtist: 'Falta o nome do artista', limit: 'Só é possível importar os primeiros {{limit}} álbuns diferentes' },
  review: {
    back: '← Importação', eyebrow: '02 · Confira os dados e as capas', titleBefore: 'Revise seus ', titleEmphasis: 'álbuns.', intro: 'O catálogo confirma automaticamente os resultados mais seguros. Revise apenas os que precisarem de atenção.', consoleLabel: 'Status da busca no catálogo', session: 'Sessão do catálogo', searched: '{{searched}} de {{total}} pesquisados', status: 'No catálogo: {{matched}} · Para revisar: {{unresolved}}', matchingHelp: 'Cada resultado confirmado já aparece na lista. As capas carregam ao mesmo tempo.', idleHelp: 'Resultados salvos aparecem na hora. As novas buscas no MusicBrainz têm um pequeno intervalo.', matching: 'Buscando no MusicBrainz…', matchUnresolved: 'Buscar {{count}} pendentes', allMatched: 'Revisão concluída', autoCorrected: 'Encontrado no catálogo e ajustado · {{confidence}}%', catalogMatchedConfidence: 'Encontrado no catálogo · {{confidence}}%', catalogMatched: 'Encontrado no catálogo', chooseMatch: 'Precisa de revisão', searchError: 'Erro ao buscar', manualDetails: 'Dados informados manualmente', notMatched: 'Precisa de revisão', editDetails: 'Editar dados', rematch: 'Buscar novamente', coverArriving: 'Buscando a capa…', coverMissingEdit: 'A capa não está no acervo. Por enquanto, mostramos uma capa genérica. Edite os dados para adicionar uma URL HTTPS.', coverMissingAdd: 'A capa não está no acervo. Por enquanto, mostramos uma capa genérica. Adicione uma URL HTTPS, se tiver.', coverFailed: 'Não foi possível buscar a capa.', retryCover: 'Tentar de novo', listening: 'Buscando no MusicBrainz…', albumTitle: 'Título do álbum', artist: 'Artista', year: 'Ano', coverUrl: 'URL HTTPS da capa', searching: 'Buscando…', findBetter: 'Buscar outra opção', doneEditing: 'Concluir edição', duplicate: 'Este álbum já aparece na coleção.', invalidCover: 'A URL da capa precisa começar com https://', matchesFor: 'Resultados para {{title}}', catalogUnsure: 'Confira os resultados.', catalogUnsureHelp: 'Escolha o álbum correto.', confidence: '{{confidence}}% de confiança', lowConfidence: 'Baixa confiança', uniqueRange: '{{albums}} · Mínimo de 2 e máximo de 100', continue: 'Escolher modo de ranking →', noMatches: 'Nenhum resultado foi encontrado no catálogo. Você pode preencher os dados manualmente.', searchFailed: 'Não foi possível buscar no catálogo. Tente novamente em instantes.',
  },
  modes: {
    quick: { name: 'Rápido', eyebrow: 'Menos comparações', description: 'Faz até três rodadas no esquema todos contra todos e combina todas as escolhas em um único cálculo.', pro: 'É o caminho mais curto até um ranking útil.', con: 'As posições do meio são aproximadas.' },
    balanced: { name: 'Equilibrado', eyebrow: 'Entre rapidez e precisão', description: 'Concentra um número fixo de comparações nos pares mais incertos ou que apareceram menos.', pro: 'Dá mais segurança sem comparar todos os pares.', con: 'Alguns pares não se enfrentam diretamente.' },
    thorough: { name: 'Minucioso', eyebrow: 'Todas as comparações', description: 'Compara cada par de discos uma vez.', pro: 'Todos os pares se enfrentam diretamente.', con: 'Pode demorar bastante com coleções grandes.' },
    recommended: 'Recomendado', back: '← Revisar álbuns', eyebrow: '03 · Escolha o modo', titleBefore: 'Quanto você quer\n', titleEmphasis: 'comparar?', intro: 'Você pode trocar de modo antes de cada rodada. Em cada duelo, escolha o disco que compraria primeiro ou declare empate.', longWarningTitle: 'Esta coleção é grande.', longWarning: 'O modo Minucioso exige {{count}} escolhas. Considere usar o Rápido ou o Equilibrado.', groupLabel: 'Modo de ranking', exactly: 'Exatamente', battles_one: '{{formattedCount}} duelo', battles_other: '{{formattedCount}} duelos', about: 'Cerca de', seedHelp: 'A ordem inicial, os desempates do modo Equilibrado e o lado de cada disco são definidos ao acaso a partir de uma semente salva.', begin: 'Começar no modo {{mode}} →', modeLabel: 'Modo {{mode}}',
  },
  duration: { seconds: '{{count}} s', minutes: '{{count}} min', hours: '{{count}} h', hoursMinutes: '{{hours}} h {{minutes}} min' },
  battle: {
    preparing: 'Preparando a rodada…', exit: '← Salvar e sair', undo: '↶ Desfazer', restart: 'Recomeçar', progress: 'Duelo {{current}}', of: 'de {{total}}', remaining: 'Cerca de {{duration}} restantes', chooseBetween: 'Escolha entre {{leftTitle}}, de {{leftArtist}}, e {{rightTitle}}, de {{rightArtist}}.', eyebrow: 'Escolha sem pensar demais', titleBefore: 'Qual disco vem ', titleEmphasis: 'primeiro?', prompt: 'Escolha o disco que você compraria primeiro ou declare empate se nenhum tiver prioridade.', chooseRecord: 'Escolher este disco', cantDecide: 'Não consigo decidir', or: 'ou', keyboard: 'Teclado:', keyboardLeft: 'para a esquerda', keyboardTie: 'para empate', keyboardRight: 'para a direita', restartConfirm: 'Recomeçar esta rodada? As escolhas salvas nesta rodada serão apagadas.',
  },
  trackReview: {
    noAlbums: 'Não há álbuns para revisar', returnResults: 'Voltar aos resultados', saveReturn: '← Salvar e voltar aos resultados', progress: '{{current}} de {{total}}', eyebrow: 'Revisão de faixas · opcional', titleLabel: 'Marque as faixas de que você gosta.', titleBefore: 'Marque as faixas de que\n', titleEmphasis: 'você gosta.', intro: 'As faixas que você não marcar não contam a favor nem contra o álbum. Use o coração para marcar suas curtidas; as faixas não são comparadas entre si.', edition: 'Edição', editionOption: '{{title}} · {{tracks}}{{date}}', loadingTracklist: 'Carregando lista de faixas', manualTitle: 'Informe um resumo do álbum', manualHelp: 'Use esta opção quando o catálogo não tiver uma edição adequada. Informe o total de faixas e quantas você curte.', totalTracks: 'Total de faixas', liked: 'Curtidas', likedTracks: 'Faixas curtidas', useCatalog: 'Usar a lista do catálogo', like: 'Curtir {{title}}', unlike: 'Remover curtida de {{title}}', likeTitle: 'Curtir', unlikeTitle: 'Remover curtida', noTracklist: 'Não encontramos uma lista de faixas adequada para este álbum.', enterManual: 'Informar totais manualmente', moreEditions: 'Ver mais edições', loadingMore: 'Carregando…', skip: 'Pular álbum não ouvido', finish: 'Concluir revisão das faixas', saveNext: 'Salvar e ir para o próximo álbum →', reviewing: 'Revisando {{title}}, de {{artist}}. Álbum {{current}} de {{total}}.', loadFailed: 'Não foi possível carregar a lista de faixas.', moreFailed: 'Não foi possível carregar mais edições.',
  },
  manualErrors: { wholeNumbers: 'Use números inteiros iguais ou maiores que zero.', oneTrack: 'Informe pelo menos uma faixa.', likedExceedsTotal: 'O número de faixas curtidas não pode ser maior que o total.' },
  results: {
    eyebrow: 'Resultado final', titleLabel: 'Você já sabe qual disco vem primeiro.', titleBefore: 'Você já sabe qual disco\nvem ', titleEmphasis: 'primeiro.', summary_one: '{{choices}} definiu o ranking {{mode}} de {{collection}}.', summary_other: '{{choices}} definiram o ranking {{mode}} de {{collection}}.', legacyTitle: 'Este ranking usa o modelo original do Solitude.', legacyBody: 'O resultado continua como você o concluiu. Faça outra rodada para usar o modelo Bradley–Terry.', viewLabel: 'Visualização do ranking', heart: 'Preferência', recordValue: 'Valor do disco', balance: 'Equilíbrio', heartWeight: 'Peso da preferência', songs: 'Músicas', heartNote: 'Calculada com base nos duelos entre discos.', recordNote: 'Aproxima a proporção de faixas curtidas de cada álbum da média da coleção, usando oito faixas como referência.', balanceNote: 'Coloca Preferência e Valor do disco na mesma escala e combina os dois conforme a proporção escolhida.', topPick: '1º lugar', heartScore: 'Preferência: {{score}}', recordScore: 'Valor do disco: {{score}}%', balanceScore: 'Equilíbrio: {{score}}', notReviewed: 'Não revisados', notReviewedBody: 'Estes álbuns não aparecem em Valor do disco até que você revise ou informe as faixas.', disagreementEyebrow: 'Quando os duelos e as faixas apontam para lados diferentes', disagreement: 'Nos duelos, {{heartAlbum}} fica à frente. Pelas faixas curtidas, há mais evidências a favor de {{trackAlbum}}.', encore: 'Revisão opcional', deeperTitle: 'Quer revisar as faixas?', deeperBody: 'Marque as faixas de que você gosta para calcular Valor do disco e Equilíbrio. Seu ranking de preferência, baseado nos duelos, não muda.', reviewSongs: 'Revisar as faixas', keepRanking: 'Manter este ranking', rankAgainNew: 'Refazer com o novo modelo', rankAgain: 'Fazer outra rodada', reviewSongsShort: 'Revisar faixas', backCollections: 'Voltar às coleções', undo: '↶ Desfazer última escolha',
  },
  albumArt: { missing: 'Sem capa para {{title}}, de {{artist}}', cover: 'Capa de {{title}}, de {{artist}}' },
  notices: { recovered: 'Os dados salvos estavam ilegíveis, então o Solitude abriu uma biblioteca nova.', saveFailed: 'Não foi possível salvar a última alteração. O armazenamento do navegador pode estar cheio ou indisponível.', invalidNavigation: 'A página salva não era mais válida, então o Solitude voltou para a biblioteca.' },
  fallback: { collectionMissing: 'Coleção não encontrada', nothingResume: 'Não há ranking para retomar', returnLibrary: 'Voltar à biblioteca' },
} as const satisfies LocaleResourceShape<EnglishResources>

export default ptBR
